export default {
    INIT_THEME: 'INIT_THEME',
    LOAD_PROJECTS: 'LOAD_PROJECTS',
    LOAD_PROJECTS_SUCCESS: 'LOAD_PROJECTS_SUCCESS',
    LOAD_PROJECTS_FAIL: 'LOAD_PROJECTS_FAIL',
    OPEN_PROJECT: 'OPEN_PROJECT',
    OPEN_PROJECT_SUCCESS: 'OPEN_PROJECT_SUCCESS',
    OPEN_PROJECT_FAIL: 'OPEN_PROJECT_FAIL',
}
