name: workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          node-version: '12.13.1'
      - name: Install Dependencies for Ubuntu
        run: sudo apt install build-essential libssl-dev libkrb5-dev libc++-dev
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test